development:
  adapter: postgresql
  encoding: utf8
  database: codemap_development
  pool: 5
  username: 
  password:

test: &test
  adapter: postgresql
  encoding: utf8
  database: codemap_test
  pool: 5
  username: 
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: codemap_production
  pool: 5
  username: 
  password:

cucumber:
  <<: *test